Update styles.scss
LouisBarranqueiro/reapop-theme-bootstrap pull request #4
Opened 2016-10-24 04:37 UTC by microdou

Fix to following warning:
Failed prop type: Required prop `theme.notificationsSystem.className` was not specified in `NotificationsSystem`

2016-11-19 11:25 UTC, sarneeh commented
I think there is no need for inserting all the stuff that You did right there. It could be just:
```css
.notifications-system {
    /*I'm needed here*/
}
```

2016-11-19 11:26 UTC, jsardev requested changes
Review below :)

2016-11-19 11:27 UTC, jsardev requested changes

2016-11-19 11:27 UTC, sarneeh commented on src/styles/styles.scss
> +:local .notifications-system {
How about just:
```
.notifications-system {
    /*I'm needed here*/
}
```

2016-11-19 22:29 UTC, microdou commented on src/styles/styles.scss
> +:local .notifications-system {
I was just following `reapop-theme-wybo/blob/master/src/styles/styles.scss` :)

2016-11-19 22:32 UTC, sarneeh commented on src/styles/styles.scss
> +:local .notifications-system {
Hmm... I'm not sure it's a good choice. Wybo theme could have some different font styles than bootstrap. Correct me if i'm wrong :)

2016-11-21 11:55 UTC, LouisBarranqueiro commented
This is no more required. `NotificationSystem.classNames` is now optional - just update reapop module -  https://github.com/LouisBarranqueiro/reapop/releases/tag/v0.6.1

2016-11-21 11:55 UTC, closed without merging

2016-11-21 13:12 UTC, sarneeh commented
Thanks! :)